CREATE UNIQUE INDEX Modules_order_idx_key ON public.Modules USING btree (order_idx)
CREATE UNIQUE INDEX Modules_pkey ON public.Modules USING btree (module_id)
CREATE UNIQUE INDEX Media_Files_file_url_key ON public.MediaFiles USING btree (file_url)
CREATE UNIQUE INDEX Media_Files_pkey ON public.MediaFiles USING btree (file_id)
CREATE UNIQUE INDEX lovemap_sections_link_id_section_type_about_user_id_key ON public.LoveMap_Sections USING btree (link_id, section_type, about_user_id)
CREATE UNIQUE INDEX lovemap_sections_pkey ON public.LoveMap_Sections USING btree (section_id)
CREATE UNIQUE INDEX lovemap_items_pkey ON public.LoveMap_Items USING btree (item_id)
CREATE INDEX idx_lovemap_items_topic_id ON public.LoveMap_Items USING btree (topic_id)
CREATE INDEX idx_lovemap_items_updated_at ON public.LoveMap_Items USING btree (updated_at)
CREATE UNIQUE INDEX emotional_bank_rating_requests_pkey ON public.EmotionalBank_RatingRequests USING btree (request_id)
CREATE INDEX idx_emotional_bank_rating_requests_entry_id ON public.EmotionalBank_RatingRequests USING btree (entry_id)
CREATE INDEX idx_emotional_bank_rating_requests_status ON public.EmotionalBank_RatingRequests USING btree (status)
CREATE INDEX idx_emotional_bank_rating_requests_to_user_id ON public.EmotionalBank_RatingRequests USING btree (to_user_id)
CREATE UNIQUE INDEX emotional_bank_entries_pkey ON public.EmotionalBank_Entries USING btree (entry_id)
CREATE INDEX idx_emotional_bank_entries_event_datetime ON public.EmotionalBank_Entries USING btree (event_datetime)
CREATE INDEX idx_emotional_bank_entries_is_shared ON public.EmotionalBank_Entries USING btree (is_shared)
CREATE INDEX idx_emotional_bank_entries_link_id ON public.EmotionalBank_Entries USING btree (link_id)
CREATE INDEX idx_emotional_bank_entries_user_id ON public.EmotionalBank_Entries USING btree (user_id)
CREATE UNIQUE INDEX emotional_bank_partner_ratings_entry_id_user_id_key ON public.EmotionalBank_PartnerRatings USING btree (entry_id, user_id)
CREATE UNIQUE INDEX emotional_bank_partner_ratings_pkey ON public.EmotionalBank_PartnerRatings USING btree (rating_id)
CREATE INDEX idx_emotional_bank_partner_ratings_entry_id ON public.EmotionalBank_PartnerRatings USING btree (entry_id)
CREATE INDEX idx_emotional_bank_partner_ratings_user_id ON public.EmotionalBank_PartnerRatings USING btree (user_id)
CREATE UNIQUE INDEX Users_pkey ON public.Users USING btree (user_id)
CREATE UNIQUE INDEX Users_user_id_key ON public.Users USING btree (user_id)
CREATE UNIQUE INDEX User_Answers_attempt_id_question_id_selected_option_id_key ON public.User_Answers USING btree (attempt_id, question_id, selected_option_id)
CREATE UNIQUE INDEX User_Answers_pkey ON public.User_Answers USING btree (user_answer_id)
CREATE UNIQUE INDEX Tests_pkey ON public.Tests USING btree (test_id)
CREATE UNIQUE INDEX Answer_Options_pkey ON public.Answer_Options USING btree (option_id)
CREATE UNIQUE INDEX Answer_Options_question_id_order_in_question_key ON public.Answer_Options USING btree (question_id, order_in_question)
CREATE UNIQUE INDEX Links_pkey1 ON public.Links USING btree (link_id)
CREATE UNIQUE INDEX user_link_unique ON public.Links USING btree (LEAST(user1_id, user2_id), GREATEST(user1_id, user2_id))
CREATE UNIQUE INDEX lovemap_topics_pkey ON public.LoveMap_Topics USING btree (topic_id)
CREATE INDEX idx_lovemap_topics_section_id ON public.LoveMap_Topics USING btree (section_id)
CREATE UNIQUE INDEX Messages_pkey ON public.Messages USING btree (message_id)
CREATE UNIQUE INDEX Questions_pkey ON public.Questions USING btree (question_id)
CREATE UNIQUE INDEX Questions_test_id_order_in_test_key ON public.Questions USING btree (test_id, order_in_test)
CREATE UNIQUE INDEX Theory_Blocks_pkey ON public.TheoryBlocks USING btree (theory_id)
CREATE UNIQUE INDEX Theory_Blocks_theory_order_key ON public.TheoryBlocks USING btree (theory_order)
CREATE UNIQUE INDEX User_Test_Attempts_pkey ON public.User_TestAttempts USING btree (attempt_id)